spring.application.name=cats
spring.profiles.active=local

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/cat?createDatabaseIfNotExist=true
spring.datasource.username=
spring.datasource.password=
=======
>>>>>>> refs/heads/main
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080