# Connection to MySQL DB
spring.datasource.url=jdbc:mysql://${MYSQL_HOSTNAME}:3306/cats?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Session is connecting the java program to db
# false connection to the DB pool conserved
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Load data.sql into MySQL after Hibernate has created the tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Force the underlying JavaMail library to print the entire SMTP traffic to System.out
spring.mail.properties.mail.debug=true
#app.mail.from=${MAIL_FROM}
app.mail.from=xin.xian.quek@gmail.com
# Application URLs
app.base-url=http://100.53.237.177:8080
app.login-path=/login


# Spring Boot Mail Settings for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devil.87.dec@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true